name: Lint and Test Charts

on:
    pull_request:
    workflow_dispatch:
      inputs:
        helm_version:
          description: 'helm version to test (default = latest)'
          default: 'latest'
          required: false
          type: string

jobs:
    lint-test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                fetch-depth: 0

            - name: Set up Helm
              uses: azure/setup-helm@v3
              with:
                version: ${{ github.event.inputs.helm_version || 'latest' }}
